# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 13:20
from __future__ import unicode_literals

import ca.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(verbose_name='Public Key')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='Private Key')),
                ('saved_password', models.TextField(blank=True, null=True)),
                ('common_name', models.CharField(max_length=128, verbose_name='Common Name')),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expired_at', models.DateTimeField(db_index=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('', 'No Reason'), ('aa_compromise', 'Attribute Authority Compromised'), ('affiliation_changed', 'Affiliation Changed'), ('ca_compromise', 'CA Compromised'), ('certificate_hold', 'On Hold'), ('cessation_of_operation', 'Cessation of Operation'), ('key_compromise', 'Key Compromised'), ('privilege_withdrawn', 'Privilege Withdrawn'), ('remove_from_crl', 'Removed from CRL'), ('superseded', 'Superseded'), ('unspecified', 'Unspecified')], max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(verbose_name='Public Key')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='Private Key')),
                ('saved_password', models.TextField(blank=True, null=True)),
                ('common_name', models.CharField(max_length=128, verbose_name='Common Name')),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expired_at', models.DateTimeField(db_index=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('', 'No Reason'), ('aa_compromise', 'Attribute Authority Compromised'), ('affiliation_changed', 'Affiliation Changed'), ('ca_compromise', 'CA Compromised'), ('certificate_hold', 'On Hold'), ('cessation_of_operation', 'Cessation of Operation'), ('key_compromise', 'Key Compromised'), ('privilege_withdrawn', 'Privilege Withdrawn'), ('remove_from_crl', 'Removed from CRL'), ('superseded', 'Superseded'), ('unspecified', 'Unspecified')], max_length=32, null=True)),
                ('name', models.CharField(max_length=32, unique=True, validators=[ca.core.validators.validate_ca_name])),
                ('description', models.TextField()),
                ('child_issuer_alt_name', models.TextField(blank=True, null=True, validators=[ca.core.validators.validate_general_name_multiline], verbose_name='Issuer AltName')),
                ('child_issuer_url', models.URLField(blank=True, null=True, verbose_name='Issuer URL')),
                ('child_crl_url', models.TextField(blank=True, null=True, validators=[ca.core.validators.validate_url_multiline], verbose_name='CRL URLs')),
                ('child_ocsp_url', models.URLField(blank=True, null=True, verbose_name='OCSP URL')),
                ('ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_ca', to='core.CertificateAuthority', verbose_name='CA (Parent)')),
                ('ocsp_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocsp_parent', to='core.Certificate', verbose_name='OCSP Certificate')),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
            },
        ),
        migrations.CreateModel(
            name='ExtendedKeyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=32, unique=True, verbose_name='OID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Extended Key Usage',
            },
        ),
        migrations.CreateModel(
            name='KeyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=32, unique=True, verbose_name='OID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Key Usage',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
                ('key_usage_critical', models.BooleanField(default=True, verbose_name='KeyUsage Critical')),
                ('extended_key_usage_critical', models.BooleanField(default=False, verbose_name='ExtendedKeyUsage Critical')),
                ('cn_in_san', models.BooleanField(default=True, verbose_name='CN in SAN')),
                ('key_size', models.IntegerField(default=4096, validators=[ca.core.validators.validate_key_size], verbose_name='Key Size')),
                ('expire_days', models.IntegerField(default=375, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1105)], verbose_name='Expire Days')),
                ('extended_key_usage_values', models.ManyToManyField(to='core.ExtendedKeyUsage', verbose_name='ExtendedKeyUsage Values')),
                ('key_usage_values', models.ManyToManyField(to='core.KeyUsage', verbose_name='KeyUsage Values')),
            ],
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.CertificateAuthority', verbose_name='Certificate Authority'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='managers',
            field=models.ManyToManyField(related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Profile'),
        ),
    ]
